### ISSUE TITLE
Instructions to creating bundlers with external JS libraries

### ISSUE THREAD

**Issue by stakanich** [gapitio/gapit-htmlgraphics-panel#112]
Hi! I tried to add some code with sheetjs to my html-panel and found out that it doesn't allow to import dependencies in <script> tag.
I looked at other issues and understood that I need to use bundler to add dependencies. But when I look on the page of [bundlers](https://gapit-htmlgraphics-panel.gapit.io/docs/projects/#bundlers) I see few bundlers for popular frameworks and libraries and nothing about how to create own.

Please, any instructions to how to add own dependencies to a panel. Thanks in advance!

**Comment by ZuperZee** [comment]
Adding dependencies to one of the bundlers can be done with `npm install package-name`. [video.js](https://javascript.plainenglish.io/how-to-use-npm-and-import-export-modules-in-javascript-31a7f66a2064) would be `npm install video.js`.

The reason why there are bundlers with different frameworks is that it requires a bit of additional configuration to add those.

Sheetjs seem a little tricky TBH, but I can see if I can create a demo repo with sheetjs.

**Comment by ZuperZee** [comment]
https://github.com/gapitio/htmlgraphics-sheetjs-example
Here is a demo repo: https://github.com/gapitio/htmlgraphics-sheetjs-example

Steps done: 
1. `npx degit https://github.com/gapitio/htmlgraphics-html-bundler-template` to get the template
2. `npm i --save https://cdn.sheetjs.com/xlsx-0.18.10/xlsx-0.18.10.tgz` to install sheetjs
3. `added code to onInit.ts

**Comment by ZuperZee** [comment]
Accidentally closed the issue*

**Comment by stakanich** [comment]
Thanks a lot! So, as I understood, with this repo i will need to do in grafana server:
1. npm i --save https://cdn.sheetjs.com/xlsx-0.18.10/xlsx-0.18.10.tgz
2. git clone repo
3. do steps from "Usage" chapter of readme in repo
Am I right?

**Comment by ZuperZee** [comment]
You don't have to do in the grafana server. You could do it on your computer.
But yes.

1. git clone
2. npm i
3. npm run build
4. copy dist/panel-options.json

**Comment by ZuperZee** [comment]
Did you run `npm run build`?

**Comment by stakanich** [comment]
Yes.
Should I do this?
```
npm run dev

Go to http://localhost:5173/. Change some code in ./src/onInit.ts, ./src/onRender.ts, or ./src/design/html.html, and the website will update.

When the code is ready to be uploaded to Grafana, start the build script
```

**Comment by ZuperZee** [comment]
`npm run dev` runs the code in the browser so you can see changes live while you code.
To build the code and add it to Grafana, you need to run `npm run build` and then copy the `panel-options.json` file in the dist folder to an HTMLGraphics panel in Grafana.

**Comment by stakanich** [comment]
So. That's what I did.
When I exported  panel-options.json to grafana it erased my previous html and added some button which I changed to my again.
Then I added the code which I sent upper below long-long code in onInit and got what I got O_o

**Comment by ZuperZee** [comment]
Did you change `html.html` (next to `onInit.ts) to anything?

**Comment by stakanich** [comment]
Nope. Just copied panel-options.json

**Comment by ZuperZee** [comment]
`htmlNode.getElementById("sheetjsexport")` is trying to get the an element with the id `sheetjsexport`, but the current html from `html.html` is
```
<div>
  <button>Download</button>
</div>
```

**Comment by stakanich** [comment]
Yes. And I changed it in the grafana interface to:
```
<div class="main">
    <button id="sheetjsexport"><b>Create xlsx</b></button>
</div>
```

**Comment by ZuperZee** [comment]
Modified your code to make a simple example with just data

`onInit.ts`
```js
import * as XLSX from "xlsx";
import "./style.css";

htmlNode.querySelector("button").addEventListener("click", function () {
  const worksheet = XLSX.utils.json_to_sheet([["123", "324"]]);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Data");
  XLSX.utils.sheet_add_aoa(worksheet, [["Data"]], { origin: "A1" });

  XLSX.writeFile(workbook, "MyData " + new Date().toLocaleString() + ".xlsx");
});
```

![image](https://user-images.githubusercontent.com/39485579/182906811-3947da06-70ca-4e41-8bb8-d6fffea13a84.png)

**Comment by ZuperZee** [comment]
> Yes. And I changed it in the grafana interface to:
> 
> ```
> <div class="main">
>     <button id="sheetjsexport"><b>Create xlsx</b></button>
> </div>
> ```

The `panel-options.json` overwrites it. You need to change `html.html` to have the HTML code.

**Comment by ZuperZee** [comment]
Like this
![image](https://user-images.githubusercontent.com/39485579/182907219-b211efcb-c17f-48e2-8c4f-9dadf179970c.png)

**Comment by stakanich** [comment]
So, I need to change files directly and not in the interface?

**Comment by ZuperZee** [comment]
Correct. The _bundler_ handles all the settings. If you want to change a setting change the setting in the `panelOptions.config.js` or one of the files. (Some options like css, html, onRender, onInit, codeData(custom-properties.json) are changed by their respective file)

**Comment by ZuperZee** [comment]
You can also delete one of the fields in `panelOptions.config.js` which makes it be decided by the panel (interface).
Some extra steps are needed for css, html, onRender, onInit, codeData(custom-properties.json).
`scripts/panelOptions.js` remove the `IN_PATHS` fields as well.

**Comment by ZuperZee** [comment]
![image](https://user-images.githubusercontent.com/39485579/182908736-7898e36b-2f53-442d-b0a7-1511a4f9a67f.png)

`onInit`
```js
import * as XLSX from "xlsx";
import "./style.css";

htmlNode.querySelector("#sheetjsexport").addEventListener("click", function () {
  const worksheet = XLSX.utils.json_to_sheet([
    ["123"],
    ["321"],
    ["nice"],
    [new Date().toISOString()],
  ]);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Data");
  XLSX.utils.sheet_add_aoa(worksheet, [["Data"]], { origin: "A1" });

  XLSX.writeFile(workbook, "MyData " + new Date().toLocaleString() + ".xlsx");
});
```

`html.html`
```html
<div class="main">
  <button id="sheetjsexport"><b>Create xlsx</b></button>
</div>

```

**Comment by stakanich** [comment]
Yes! It works! Thanks!
Exporting file to grafana makes my browser freeze for a minute or two, but at least it works!

**Comment by ZuperZee** [comment]
exporting the XLSX file?

**Comment by stakanich** [comment]
No. Exporting panel-options.json

**Comment by stakanich** [comment]
*Importing. Sorry.

**Comment by ZuperZee** [comment]
Oh yeah. The sheetjs/XLSX is pretty big (like 300kb)

**Comment by ZuperZee** [comment]
Depending on what you're trying to do. It might be better to export a .csv file instead of a .xlsx file. .csv files are much easier to make and can be made with a lot less javascript.

**Comment by stakanich** [comment]
I will think about ways to optimize things. Big thanks for helping.

**Comment by ZuperZee** [comment]
Closing as it seems answered.
_Please as questions in [discussions](https://github.com/gapitio/gapit-htmlgraphics-panel/discussions) :D_
