### ISSUE TITLE
Replace deprecated getLocationSrv

### ISSUE THREAD

**Issue by PhilippDehner** [gapitio/gapit-htmlgraphics-panel#180]
**What would you like to be added**:

`locationService` should be added to the available Elements in the code blocks and `getLocationSrv` should be removed

**Why is this needed**:

`getLocationSrv` is deprecated.

**Comment by ZuperZee** [comment]
Is this related to the examples on the website or does locationService not work?
https://gapit-htmlgraphics-panel.gapit.io/docs/references/#locationservice

**Comment by PhilippDehner** [comment]
> Is this related to the examples on the website or does locationService not work? https://gapit-htmlgraphics-panel.gapit.io/docs/references/#locationservice

Yes, it works, but why is the old method still in the options? Why is it not replaced? So it does not have to be from the htmlGraphics and there is not deprecated method

**Comment by ZuperZee** [comment]
I don't want the old panels using getLocationSrv to stop working. I might remove getLocationSrv once Grafana removes it. It's currently still supported on Grafana's latest release https://github.com/grafana/grafana/blob/401265522e584e4e71a1d92d5af311564b1ec33e/packages/grafana-runtime/src/services/LocationSrv.ts#L70

**Comment by PhilippDehner** [comment]
Ah okay. Yes, I understand.
