### ISSUE TITLE
OnRender not executing for new data

### ISSUE THREAD

**Issue by psheehymn** [gapitio/gapit-htmlgraphics-panel#186]
**What happened**:
We have an HTML Graphics panel used as the main header for all of our dashboards. It just displays a banner, but under the covers runs some complex queries that are beyond what is supported through the Query variable definition interfaces and stores the values into Constant variables that are then available to other panels (essentially externally loaded Query variables).

The banner displays the currently selected time range, retrieving it from the Grafana global variables, formatting it and updating the HTML. The JavaScript for this is contained in the onRender section, which, as we understand it, should execute whenever new data is available, such as a change in the time range selection. However, the panel does NOT refresh the majority of the time when the time range changes (meaning the variables are not being updated to reflect the range change). I even added a _panelupdate_ event listener in the JS to try to force it, but it is still not executing.

**What you expected to happen**:
When the time range is changes, the panel should execute the JS in the onRender, which would refresh the variables and the displayed time.

**How to reproduce it (as minimally and precisely as possible)**:
I have attached an importable dashboard with a stripped-down version of the panel which still includes the time refresh code (but without the queries or variable updates).

[Header Not Refreshing Issue-1713546520774.json](https://github.com/gapitio/gapit-htmlgraphics-panel/files/15043512/Header.Not.Refreshing.Issue-1713546520774.json)

**Anything else we need to know?**:
Nothing I can think of pending any questions.

**Environment**:

- Grafana version: v10.4.0
- Plugin (gapit-htmlgraphics-panel) version: 2.1.1
- Data source type & version: None
- OS Grafana is installed on: RHEL 8.9
- User OS & Browser: Windows/Chrome
- Grafana plugins: N/A
- Others: N/A

**Comment by ZuperZee** [comment]
I'm struggling to reproduce the bug you're talking about.
![a1](https://github.com/gapitio/gapit-htmlgraphics-panel/assets/39485579/ccca402f-d9da-4472-977c-efaaa3d8351c)

I've noticed that you are using the [`panelupdate event `](https://gapit-htmlgraphics-panel.gapit.io/docs/references/#panelupdate-event) inside `onRender` (`htmlNode.addEventListener('panelupdate', refreshPanel);`. This is usually never intended as you'll create a lot of event listeners.
Move the entire code into `onInit` or remove `htmlNode.addEventListener('panelupdate', refreshPanel);`.

The [`panelupdate event `](https://gapit-htmlgraphics-panel.gapit.io/docs/references/#panelupdate-event) is meant to be used inside `onInit` so it can simulate how `onRender` is triggered.
In the source code `onRender` and `panelupdate event` is triggered at the same place https://github.com/gapitio/gapit-htmlgraphics-panel/blob/5c05b16ed34b377748f0ad17421ff4c603e1f247/src/HTMLPanel.tsx#L267-L268

**Comment by psheehymn** [comment]
I had only added the addListener code when we noticed this issue to try to work around it, but if I am reading you correctly, having it create multiple listeners that get called along with the onRender might actually cause an issue.

I didn’t understand that the listener was primarily for the onInit when I first starting using the panel (you actually clued me in on that in a previous ticket). Since this is intermittent, I’ll go back and look to see if it’s only happening on dashboards where I am using other HTML Graphics panels (we use your plugin a lot!) and if perhaps I have some older panels that erroneously have the panelupdate event<https://urldefense.com/v3/__https:/gapit-htmlgraphics-panel.gapit.io/docs/references/*panelupdate-event__;Iw!!IqUcNYopQPk7!KVZJenE-QKCRZg37y33FmQIrE1A4RVtjieAPo-22b1gdHRA-kE_gkyhmmSh5cuVCvNa35YYOwGWThL2XXte2ew2DGSuf$> in the onRender.

I’ll update this ticket if I find that is the case.

Patrick M. Sheehy | Portal Monitoring Program Management, Optum Digital
M (507) 251-9899
***@***.******@***.***> | www.myuhc.com<http://www.myuhc.com/>

Helping People Live Healthier Lives®
■ Integrity ■ Compassion ■ Relationships ■ Innovation ■ Performance

**Comment by psheehymn** [comment]
This does appear to have been a multiple-listener issue. Closing...
