### ISSUE TITLE
Support for componentWillUnmount.

### ISSUE THREAD

**Issue by n-arakawa** [gapitio/gapit-htmlgraphics-panel#34]
I use "setInterval" in "OnInit".
Hope to have a chance to "clearInterval" just befor the panel will be destroyed.

On the same time, I want to know how to share timerid  between "OnInit" and other code.

**Comment by ZuperZee** [comment]
I'll see what can be done with the unmount function.

The share onInit with other code (I assume onRender) you can bind it to the htmlNode. _Which is what I usually do._

https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

_onInit_
```ts
const timerId = 2;
htmlNode.lastElementChild.dataset.timerId = timerId;
```

_onRender_
```ts
const timerId = htmlNode.lastElementChild.dataset.timerId;
console.log(timerId);
```

_Here is an example_

<details><summary>JSON Options</summary>
<p>

You can import this code in the import section of the htmlgraphics panel

```json
{
    "add100Percentage": true,
    "centerAlignContent": true,
    "overflow": "visible",
    "SVGBaseFix": true,
    "codeData": "{\n  \"text\": \"Random text\"\n}",
    "css": "* {\n  font-family: Open Sans;\n}\n",
    "html": "<div id=\"test\" />\n",
    "renderOnMount": true,
    "onRender": "htmlNode.querySelector(\"div\").textContent = htmlNode.lastElementChild.dataset.timerId;",
    "dynamicData": false,
    "panelupdateOnMount": true,
    "onInit": "const timerId = 2;\nhtmlNode.lastElementChild.dataset.timerId = timerId;\n"
}
```

</p>
</details>

**Comment by n-arakawa** [comment]
Shareing variables with data attribute wiorks fine! Thanks lot.

If you have a plan to add Unmount functutionalioty, 
I hope to integrate OnInit, OnRender,WillUnmount to one text fileld.

> let timer_id
> function OnInit(){
>  timer_id= setInterval ..
> }
> function OnRendet(){
>  Rendering codes goes here.
> }
> function WillUnmount(){
>  clear_interval(timer)id)
> }

This style allows
 - closure variables
 - One file Cut&Pase editing!!

**Comment by n-arakawa** [comment]
Simplified implementation structure without error handling could be

```js
// user define code from configuration panel
const user_code = `
let i;
const onInit = () => { i=1;}
const onRender = () => { console.log(i, htmlNode);}
const onWillUnmount = () => { console.log(i);}
return [onInit, onRender, onWillUnmount]

`

// htmlNode, data, codeData, codeData, options, theme, getTemplateSrv, getLocationSrv, htmlGraphics
const [onInit, onRender, onWillUnmount] = (new Function('htmlNode', user_code))('dummy_html_node')

// use generated code
onInit()
onRender()
onWillUnmount()

```

**Comment by ZuperZee** [comment]
I would suggest checking out https://github.com/gapitio/htmlgraphics-svg-bundler-template
It generates the panel-options which makes it pretty easy to copy paste it in.

There is an event https://github.com/gapitio/gapit-htmlgraphics-panel#panelupdate-event if you want to make everything in the onInit code. `panelupdate` is pretty much the same as onRender.

The unMount will also be an event (if I'm able to xD) and can be used in the onInit as well.

Events are handy if you're working on something like [Svelte](https://github.com/gapitio/htmlgraphics-svelte-bundler-template), Solid, React, ETC. You can also use it to have all the variables available in the onRender code aswell as onInit code.

**Comment by n-arakawa** [comment]
Thank you for  good suggestions.

I 'm looking forward to have  unMount  on htmlNode in near future.

For a while, I'll check   `htmlgraphics-svelte-bundler-template`
