### ISSUE TITLE
How to import external js resources

### ISSUE THREAD

**Issue by XiaoyuZhann** [gapitio/gapit-htmlgraphics-panel#41]
**What would you like to be added**:Import external js resources

**Why is this needed**:`When using grafana, I need to insert live video surveillance, the native tag <video> does not support this`

**E.g**:`<script src=“http: //vjs.zencdn.net/5.8.8/video.js”></script>`

**Comment by ZuperZee** [comment]
For now the easiest is to use a [bundler](https://gapit-htmlgraphics-panel.gapit.io/docs/projects/#bundlers).
You can use the video.js with  `npm install --save-dev video.js` with the bundler.
Currently script tags can't really be used.

**Comment by ZuperZee** [comment]
Made a [repo](https://github.com/gapitio/video.js-example) with the video.js package.
You can try it by copying [panel-options.json](https://raw.githubusercontent.com/gapitio/video.js-example/main/dist/panel-options.json) into Import/export -> Panel options 
![image](https://user-images.githubusercontent.com/39485579/134477700-2e8e3f77-d602-4b76-a1f6-a35bbfa3fd45.png)

The icons won't work until I've released v1.4.0 of the plugin. I made a new [feature](https://github.com/gapitio/gapit-htmlgraphics-panel/pull/44) that added rootCSS, but won't be available until v1.4.0.

v1.4.0 of the plugin will be released once v8.2.0 of grafana is released.

**Comment by ZuperZee** [comment]
I won't be adding a way to directly import external packages, but bundlers are a workaround.

**Comment by XiaoyuZhann** [comment]
OK, thanks

**Comment by XiaoyuZhann** [comment]
> 我不会添加直接导入外部包的方法，但打包器是一种解决方法。
> 
> _我没有找到实现它的好方法。_

OK, thanks

**Comment by XiaoyuZhann** [comment]
OK, thanks

**Comment by ZuperZee** [comment]
Also made a video example with Svelte
https://github.com/gapitio/htmlgraphics-video-example

The onInit code for Svelte = 6.07 KB
The onInit code for Video.js =  559 KB

The CSS for video.js is also a lot more.
