### ISSUE TITLE
htmlNode.createElement("option") not working

### ISSUE THREAD

**Issue by RoniPaslan** [gapitio/gapit-htmlgraphics-panel#99]
var json = JSON.parse(xhr.responseText); 
var selected_eport = htmlNode.getElementById("select_report");
                selected_eport.innerHTML = "";
                var option = htmlNode.createElement("option");
                option.text = "== SELECT REPORT ==";
                selected_eport.add(option);
                for (var i = 0; i < json.length; i++) {
                    var option = htmlNode.createElement("option");
                    option.text = json[i].REPORT_NAME;
                    option.value = json[i].REPORT_ID;
                    selected_eport.add(option);
                }

**Comment by ZuperZee** [comment]
htmlNode is a [ShadowRoot](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot), but [createElement](https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement) is a [document](https://developer.mozilla.org/en-US/docs/Web/API/Document) method.

Changing `htmlNode.createElement` to `document.createElement` should do it.

```js
var json = JSON.parse(xhr.responseText);
var selected_eport = htmlNode.getElementById("select_report");
selected_eport.innerHTML = "";
var option = document.createElement("option");
option.text = "== SELECT REPORT ==";
selected_eport.add(option);
for (var i = 0; i < json.length; i++) {
  var option = document.createElement("option");
  option.text = json[i].REPORT_NAME;
  option.value = json[i].REPORT_ID;
  selected_eport.add(option);
}
```

**Comment by ZuperZee** [comment]
Closing as this seems resolved.
